### PR TITLE
Feature/updating vehicle seed db

### LINKED ISSUE #9: Seeding Vehicles Database

### PR DESCRIPTION
**Pull request by wangscs**
Closes #9

### CODE REVIEW

**Review by GannonDeWalt — APPROVED** [review]
Looks good

**Review by ammitchky — APPROVED** [review]
looks good

**Review by raaedk — APPROVED** [review]
looks good

**Review by rmuehler — APPROVED** [review]
Looks good, possible could duplicate the username/password migration?

**Pull request merged**
